name = "NO TIENE NOMBREW"
author = "erodt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b75e9ae38e430e18fd89cac47de5c9cbf7c87a23588496dcb51c7d171e21f022"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
