name = "NO TIENE NOMBREW"
author = "erodt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "113d34ff49591cadcb12aa498eb5ea4e640f47b8cb4b6389f2ca82078189a647"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
