name = "NO TIENE NOMBREW"
author = "erodt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84ab04ec6d3dfa60015e6c557aaec6b9b712c2a89f3ff330aea77d952dfcc24f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
