#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.biomesoplenty]
			fir = true
			pine = true
			maple = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			empyreal = true

		[types.wood_type.environmental]
			wisteria = true

		[types.leaves_type.biomesoplenty]
			null = true
			origin = true
			flowering_oak = true
			cypress = true
			snowblossom = true
			rainbow_birch = true
			fir = true
			pine = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			empyreal = true

		[types.leaves_type.environmental]
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

#Disables specific entries
[entries]

		[entries.wood_type.create]
			window = false
			window_pane = false

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.unusual_furniture]
			drawer = true
			railing = true
			celling_lamp = true
			coffee_table = true
			beam = true
			carved = true
			stool = true
			table = true
			shelf = true
			open_riser_stairs = true
			bench = true
			chair = true

		[entries.wood_type.handcrafted]
			cupboard = false
			drawer = false
			counter = true
			fancy_bed = true
			desk = true
			nightstand = true
			dining_bench = true
			bench = true
			couch = true
			table = true
			chair = true
			side_table = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.leaves_type.woodworks]
			leaf_pile = false
